import request from '../../middleware/request';
const endPoint = 'account';

const LOGIN_ACCOUNT_LOADING = 'LOGIN_ACCOUNT_LOADING';
const LOGIN_ACCOUNT_SUCCESS = 'LOGIN_ACCOUNT_SUCCESS';
const LOGIN_ACCOUNT_ERROR = 'LOGIN_ACCOUNT_ERROR';

const LOGOUT_ACCOUNT_LOADING = 'LOGOUT_ACCOUNT_LOADING';
const LOGOUT_ACCOUNT_SUCCESS = 'LOGOUT_ACCOUNT_SUCCESS';
const LOGOUT_ACCOUNT_ERROR = 'LOGOUT_ACCOUNT_ERROR';
const LOGOUT_ACCOUNT_TO_APP = 'LOGOUT_ACCOUNT_TO_APP';

const CREATE_ACCOUNT_LOADING = 'CREATE_ACCOUNT_LOADING'; 
const CREATE_ACCOUNT_SUCCESS = 'CREATE_ACCOUNT_SUCCESS'; 
const CREATE_ACCOUNT_ERROR = 'CREATE_ACCOUNT_ERROR'; 

const VALIDATE_EMAIL_ACCOUNT_LOADING = 'VALIDATE_EMAIL_ACCOUNT_LOADING';
const VALIDATE_EMAIL_ACCOUNT_SUCCESS = 'VALIDATE_EMAIL_ACCOUNT_SUCCESS';
const VALIDATE_EMAIL_ACCOUNT_FAILED = 'VALIDATE_EMAIL_ACCOUNT_FAILED';

const CLEAR_ACCESS_ACCOUNT = 'CLEAR_ACCESS_ACCOUNT';
const CLEAR_CREATE_ACCOUNT_ERROR = 'CLEAR_CREATE_ACCOUNT_ERROR';
const CLEAR_LOGIN_ACCOUNT_ERROR = 'CLEAR_LOGIN_ACCOUNT_ERROR';

const REQUEST_RESET_PASSWORD_LOADING = 'REQUEST_RESET_PASSWORD_LOADING';
const REQUEST_RESET_PASSWORD_SUCCESS = 'REQUEST_RESET_PASSWORD_SUCCESS';
const REQUEST_RESET_PASSWORD_ERROR = 'REQUEST_RESET_PASSWORD_ERROR';

const PROCESS_RESET_PASSWORD_LOADING = 'PROCESS_RESET_PASSWORD_LOADING';
const PROCESS_RESET_PASSWORD_SUCCESS = 'PROCESS_RESET_PASSWORD_SUCCESS';
const PROCESS_RESET_PASSWORD_ERROR = 'PROCESS_RESET_PASSWORD_ERROR';

const ACCOUNT_ENTRY_ORGANIZE_CART_LOADING = 'ACCOUNT_ENTRY_ORGANIZE_CART_LOADING';
const ACCOUNT_ENTRY_ORGANIZE_CART_SUCCESS = 'ACCOUNT_ENTRY_ORGANIZE_CART_SUCCESS';
const ACCOUNT_ENTRY_ORGANIZE_CART_ERROR = 'ACCOUNT_ENTRY_ORGANIZE_CART_ERROR';

function register(data) {
  return request(`${endPoint}/register`, data);
}

export {
  CREATE_ACCOUNT_LOADING,
  CREATE_ACCOUNT_SUCCESS,
  CREATE_ACCOUNT_ERROR,

  LOGIN_ACCOUNT_LOADING,
  LOGIN_ACCOUNT_SUCCESS,
  LOGIN_ACCOUNT_ERROR,

  LOGOUT_ACCOUNT_LOADING,
  LOGOUT_ACCOUNT_SUCCESS,
  LOGOUT_ACCOUNT_ERROR,
  LOGOUT_ACCOUNT_TO_APP,

  VALIDATE_EMAIL_ACCOUNT_LOADING,
  VALIDATE_EMAIL_ACCOUNT_SUCCESS,
  VALIDATE_EMAIL_ACCOUNT_FAILED,

  CLEAR_ACCESS_ACCOUNT,
  CLEAR_CREATE_ACCOUNT_ERROR,
  CLEAR_LOGIN_ACCOUNT_ERROR,

  REQUEST_RESET_PASSWORD_LOADING,
  REQUEST_RESET_PASSWORD_SUCCESS,
  REQUEST_RESET_PASSWORD_ERROR,

  PROCESS_RESET_PASSWORD_LOADING,
  PROCESS_RESET_PASSWORD_SUCCESS,
  PROCESS_RESET_PASSWORD_ERROR,

  ACCOUNT_ENTRY_ORGANIZE_CART_LOADING,
  ACCOUNT_ENTRY_ORGANIZE_CART_SUCCESS,
  ACCOUNT_ENTRY_ORGANIZE_CART_ERROR,

  register,
}