const ADD_ADDRESS_LOADING = 'ADD_ADDRESS_LOADING';
const ADD_ADDRESS_SUCCESS = 'ADD_ADDRESS_SUCCESS';
const ADD_ADDRESS_ERROR = 'ADD_ADDRESS_ERROR';

const LIST_ADDRESS_LOADING = 'LIST_ADDRESS_LOADING';
const LIST_ADDRESS_SUCCESS = 'LIST_ADDRESS_SUCCESS';
const LIST_ADDRESS_ERROR = 'LIST_ADDRESS_ERROR';

const SET_VIEW_ADDRESS = 'SET_VIEW_ADDRESS';

export {
  ADD_ADDRESS_LOADING,
  ADD_ADDRESS_SUCCESS,
  ADD_ADDRESS_ERROR,

  LIST_ADDRESS_LOADING,
  LIST_ADDRESS_SUCCESS,
  LIST_ADDRESS_ERROR,

  SET_VIEW_ADDRESS,
};