const SET_SERVICE_OPTION_PICKUP = 'SET_SERVICE_OPTION_PICKUP';
const SET_SERVICE_OPTION_DELIVERY = 'SET_SERVICE_OPTION_DELIVERY';

const SET_RX_UPLOAD_REQUIRED_TRUE = 'SET_RX_UPLOAD_REQUIRED_TRUE';
const SET_RX_UPLOAD_REQUIRED_FALSE = 'SET_RX_UPLOAD_REQUIRED_FALSE';
const SET_RX_UPLOAD_FILES_UPDATED = 'SET_RX_UPLOAD_FILES_UPDATED'; 
const SET_RX_UPLOAD_FILE_REMOVE = 'SET_RX_UPLOAD_FILE_REMOVE'; 

const RX_UPLOAD_FILE_LOADING = 'RX_UPLOAD_FILE_LOADING';
const RX_UPLOAD_FILE_SUCCESS = 'RX_UPLOAD_FILE_SUCCESS';
const RX_UPLOAD_FILE_ERROR = 'RX_UPLOAD_FILE_ERROR';

const RX_REMOVE_UPLOAD_FILE_LOADING = 'RX_REMOVE_UPLOAD_FILE_LOADING';
const RX_REMOVE_UPLOAD_FILE_SUCCESS = 'RX_REMOVE_UPLOAD_FILE_SUCCESS';
const RX_REMOVE_UPLOAD_FILE_ERROR = 'RX_REMOVE_UPLOAD_FILE_ERROR';

const ESUKI_PTS_GET_LOADING = 'ESUKI_PTS_GET_LOADING';
const ESUKI_PTS_GET_SUCCESS = 'ESUKI_PTS_GET_SUCCESS';
const ESUKI_PTS_GET_ERROR = 'ESUKI_PTS_GET_ERROR';

const CART_INITIATE_REDEEM_POINTS_LOADING = 'CART_INITIATE_REDEEM_POINTS_LOADING';
const CART_INITIATE_REDEEM_POINTS_SUCCESS = 'CART_INITIATE_REDEEM_POINTS_SUCCESS';
const CART_INITIATE_REDEEM_POINTS_ERROR = 'CART_INITIATE_REDEEM_POINTS_ERROR';

const FINALIZE_CART = 'FINALIZE_CART';
const FINALIZE_ADDRESS = 'FINALIZE_ADDRESS';
const FINALIZE_BRANCH = 'FINALIZE_BRANCH';

const SET_CHECKOUT_ADDRESS_DATA = 'SET_CHECKOUT_ADDRESS_DATA'; 
const ADD_CHECKOUT_ADDRESS_LOADING = 'ADD_CHECKOUT_ADDRESS_LOADING';
const ADD_CHECKOUT_ADDRESS_SUCCESS = 'ADD_CHECKOUT_ADDRESS_SUCCESS';
const ADD_CHECKOUT_ADDRESS_ERROR = 'ADD_CHECKOUT_ADDRESS_ERROR';

const PROCEED_PAYMENT_LOADING = 'PROCEED_PAYMENT_LOADING';
const PROCEED_PAYMENT_SUCCESS = 'PROCEED_PAYMENT_SUCCESS';
const PROCEED_PAYMENT_ERROR = 'PROCEED_PAYMENT_ERROR';

const CLEAR_CHECKOUT_DATA = 'CLEAR_CHECKOUT_DATA';

const serviceOption = {
  pickUp: 'PICKUP',
  delivery: 'DELIVERY'
};

const checkoutFeedBackStatus ={
  success: 'success',
  failed: 'failed',
  cancelled: 'cancelled',
};

export {
  SET_SERVICE_OPTION_PICKUP,
  SET_SERVICE_OPTION_DELIVERY,
  serviceOption,
  checkoutFeedBackStatus,

  SET_RX_UPLOAD_REQUIRED_TRUE,
  SET_RX_UPLOAD_REQUIRED_FALSE,
  SET_RX_UPLOAD_FILES_UPDATED,
  SET_RX_UPLOAD_FILE_REMOVE,

  RX_UPLOAD_FILE_LOADING,
  RX_UPLOAD_FILE_SUCCESS,
  RX_UPLOAD_FILE_ERROR,

  RX_REMOVE_UPLOAD_FILE_LOADING,
  RX_REMOVE_UPLOAD_FILE_SUCCESS,
  RX_REMOVE_UPLOAD_FILE_ERROR,

  FINALIZE_CART,
  FINALIZE_ADDRESS,
  FINALIZE_BRANCH,

  ESUKI_PTS_GET_LOADING,
  ESUKI_PTS_GET_SUCCESS,
  ESUKI_PTS_GET_ERROR,

  CART_INITIATE_REDEEM_POINTS_LOADING,
  CART_INITIATE_REDEEM_POINTS_SUCCESS,
  CART_INITIATE_REDEEM_POINTS_ERROR,

  SET_CHECKOUT_ADDRESS_DATA,
  ADD_CHECKOUT_ADDRESS_LOADING,
  ADD_CHECKOUT_ADDRESS_SUCCESS,
  ADD_CHECKOUT_ADDRESS_ERROR,

  PROCEED_PAYMENT_LOADING,
  PROCEED_PAYMENT_SUCCESS,
  PROCEED_PAYMENT_ERROR,

  CLEAR_CHECKOUT_DATA,
};