const LOCATIONS_LIST_LOADING = 'LOCATIONS_LIST_LOADING';
const LOCATIONS_LIST_SUCCESS = 'LOCATIONS_LIST_SUCCESS';
const LOCATIONS_LIST_ERROR = 'LOCATIONS_LIST_ERROR';
const SET_VIEW_REGION_ID = 'SET_VIEW_REGION_ID';

const LOCATION_STATES_LIST_LOADING = 'LOCATION_STATES_LIST_LOADING';
const LOCATION_STATES_LIST_SUCCESS = 'LOCATION_STATES_LIST_SUCCESS';
const LOCATION_STATES_LIST_ERROR = 'LOCATION_STATES_LIST_ERROR';
const SET_VIEW_STATE_ID = 'SET_VIEW_STATE_ID';
const CLEAR_LOCATION_STATES_LIST = 'CLEAR_LOCATION_STATES_LIST';

const LOCATION_BRANCHES_LIST_LOADING = 'LOCATION_BRANCHES_LIST_LOADING';
const LOCATION_BRANCHES_LIST_SUCCESS = 'LOCATION_BRANCHES_LIST_SUCCESS';
const LOCATION_BRANCHES_LIST_ERROR = 'LOCATION_BRANCHES_LIST_ERROR';

export {
  LOCATIONS_LIST_LOADING,
  LOCATIONS_LIST_SUCCESS,
  LOCATIONS_LIST_ERROR,
  SET_VIEW_REGION_ID,

  LOCATION_STATES_LIST_LOADING,
  LOCATION_STATES_LIST_SUCCESS,
  LOCATION_STATES_LIST_ERROR,
  SET_VIEW_STATE_ID,
  CLEAR_LOCATION_STATES_LIST,

  LOCATION_BRANCHES_LIST_LOADING,
  LOCATION_BRANCHES_LIST_SUCCESS,
  LOCATION_BRANCHES_LIST_ERROR,
};