const SEND_PRODUCT_INQUIRY_LOADING = 'SEND_PRODUCT_INQUIRY_LOADING';
const SEND_PRODUCT_INQUIRY_SUCCESS = 'SEND_PRODUCT_INQUIRY_SUCCESS';
const SEND_PRODUCT_INQUIRY_ERROR = 'SEND_PRODUCT_INQUIRY_ERROR';

const SEND_GENERAL_INQUIRY_LOADING = 'SEND_GENERAL_INQUIRY_LOADING';
const SEND_GENERAL_INQUIRY_SUCCESS = 'SEND_GENERAL_INQUIRY_SUCCESS';
const SEND_GENERAL_INQUIRY_ERROR = 'SEND_GENERAL_INQUIRY_ERROR';

export {
  SEND_PRODUCT_INQUIRY_LOADING,
  SEND_PRODUCT_INQUIRY_SUCCESS,
  SEND_PRODUCT_INQUIRY_ERROR,

  SEND_GENERAL_INQUIRY_LOADING,
  SEND_GENERAL_INQUIRY_SUCCESS,
  SEND_GENERAL_INQUIRY_ERROR,
};