const ORDER_HISTORY_LIST_LOADING = 'ORDER_HISTORY_LIST_LOADING'; 
const ORDER_HISTORY_LIST_SUCCESS = 'ORDER_HISTORY_LIST_SUCCESS'; 
const ORDER_HISTORY_LIST_ERROR = 'ORDER_HISTORY_LIST_ERROR';

export {
  ORDER_HISTORY_LIST_LOADING,
  ORDER_HISTORY_LIST_SUCCESS,
  ORDER_HISTORY_LIST_ERROR,
};