const PRODUCT_LIST_BY_CATEGORY_LOADING = 'PRODUCT_LIST_BY_CATEGORY_LOADING';
const PRODUCT_LIST_BY_CATEGORY_SUCCESS = 'PRODUCT_LIST_BY_CATEGORY_SUCCESS';
const PRODUCT_LIST_BY_CATEGORY_ERROR = 'PRODUCT_LIST_BY_CATEGORY_ERROR';

const PRODUCT_SEARCH_ALL_LOADING = 'PRODUCT_SEARCH_ALL_LOADING';
const PRODUCT_SEARCH_ALL_SUCCESS = 'PRODUCT_SEARCH_ALL_SUCCESS';
const PRODUCT_SEARCH_ALL_FAILED = 'PRODUCT_SEARCH_ALL_FAILED';
const CLEAR_PRODUCT_SEARCH_ALL = 'CLEAR_PRODUCT_SEARCH_ALL';

export {
  PRODUCT_LIST_BY_CATEGORY_LOADING,
  PRODUCT_LIST_BY_CATEGORY_SUCCESS,
  PRODUCT_LIST_BY_CATEGORY_ERROR,

  PRODUCT_SEARCH_ALL_LOADING,
  PRODUCT_SEARCH_ALL_SUCCESS,
  PRODUCT_SEARCH_ALL_FAILED,
  CLEAR_PRODUCT_SEARCH_ALL,
};