const SET_SELECTED_CATEGORY = 'SET_SELECTED_CATEGORY';
const SET_SELECTED_CATEGORY_ONSUCCESS_CATEGORY_LIST = 'SET_SELECTED_CATEGORY_ONSUCCESS_CATEGORY_LIST';

const CATEGORY_LIST_LOADING = 'CATEGORY_LIST_LOADING'; 
const CATEGORY_LIST_SUCCESS = 'CATEGORY_LIST_SUCCESS'; 
const CATEGORY_LIST_ERROR = 'CATEGORY_LIST_ERROR'; 

const CATEGORY_BANNER_TOP_GET_LOADING = 'CATEGORY_BANNER_TOP_GET_LOADING';
const CATEGORY_BANNER_TOP_GET_SUCCESS = 'CATEGORY_BANNER_TOP_GET_SUCCESS';
const CATEGORY_BANNER_TOP_GET_ERROR = 'CATEGORY_BANNER_TOP_GET_ERROR';

const CATEGORY_BANNER_BOTTOM_GET_LOADING = 'CATEGORY_BANNER_BOTTOM_GET_LOADING';
const CATEGORY_BANNER_BOTTOM_GET_SUCCESS = 'CATEGORY_BANNER_BOTTOM_GET_SUCCESS';
const CATEGORY_BANNER_BOTTOM_GET_ERROR = 'CATEGORY_BANNER_BOTTOM_GET_ERROR';

const SET_CATEGORY_BANNER_TOP = 'SET_CATEGORY_BANNER_TOP';
const SET_CATEGORY_BANNER_BOTTOM = 'SET_CATEGORY_BANNER_BOTTOM';

const categoryBannerType = {
  categoryTop: 'CATEGORY_TOP',
  categoryBottom: 'CATEGORY_BOTTOM',
};

export {
  SET_SELECTED_CATEGORY,
  SET_SELECTED_CATEGORY_ONSUCCESS_CATEGORY_LIST,
  CATEGORY_LIST_LOADING,
  CATEGORY_LIST_SUCCESS,
  CATEGORY_LIST_ERROR,

  CATEGORY_BANNER_TOP_GET_LOADING,
  CATEGORY_BANNER_TOP_GET_SUCCESS,
  CATEGORY_BANNER_TOP_GET_ERROR,

  SET_CATEGORY_BANNER_TOP,
  SET_CATEGORY_BANNER_BOTTOM,

  categoryBannerType,
};